// <auto-generated />
using System;
using GameNet.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameNet.Server.Persistence.Migrations
{
    [DbContext(typeof(GameNetDbContext))]
    partial class GameNetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameNet.Server.Infrastructure.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("IX_audit_entries_IdempotencyKey");

                    b.HasIndex("OccurredAtUtc", "Operation")
                        .HasDatabaseName("IX_audit_entries_OccurredAtUtc_Operation");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("IX_audit_entries_ReferenceType_ReferenceId");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("GameNet.Server.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("LeaseExpiresAtUtc", "Id");

                    b.HasIndex("PublishedAtUtc", "OccurredAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("GameNet.Server.Persistence.Entities.AgentConnectionLease", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at_utc");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_token");

                    b.Property<string>("StationState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("station_state");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DeviceId");

                    b.HasIndex("LeaseExpiresAtUtc", "DeviceId")
                        .HasDatabaseName("IX_agent_connection_leases_Expires_Device");

                    b.ToTable("agent_connection_leases", (string)null);
                });

            modelBuilder.Entity("GameNet.Server.Persistence.Entities.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("LastAuthenticatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_authenticated_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_agent_credentials_ActiveDevice")
                        .HasFilter("revoked_at_utc IS NULL");

                    b.HasIndex("DeviceId", "CreatedAtUtc")
                        .HasDatabaseName("IX_agent_credentials_Device_Created");

                    b.ToTable("agent_credentials", (string)null);
                });

            modelBuilder.Entity("GameNet.Server.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_token");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("scope");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.OperatorUser", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Username").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("username");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("display_name");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("password_hash");
                    b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                    b.Property<int>("FailedLoginCount").HasColumnType("integer").HasColumnName("failed_login_count");
                    b.Property<DateTimeOffset?>("LockoutUntilUtc").HasColumnType("timestamp with time zone").HasColumnName("lockout_until_utc");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                    b.Property<DateTimeOffset?>("LastLoginAtUtc").HasColumnType("timestamp with time zone").HasColumnName("last_login_at_utc");
                    b.HasKey("Id").HasName("pk_operator_users");
                    b.HasIndex("Username").IsUnique().HasDatabaseName("ix_operator_users_username");
                    b.ToTable("operator_users", (string)null);
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Code").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("code");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("name");
                    b.HasKey("Id").HasName("pk_roles");
                    b.HasIndex("Code").IsUnique().HasDatabaseName("ix_roles_code");
                    b.ToTable("roles", (string)null);
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.AuthSession", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.Property<string>("Jti").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("jti");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                    b.Property<DateTimeOffset>("ExpiresAtUtc").HasColumnType("timestamp with time zone").HasColumnName("expires_at_utc");
                    b.Property<DateTimeOffset?>("RevokedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("revoked_at_utc");
                    b.HasKey("Id").HasName("pk_auth_sessions");
                    b.HasIndex("Jti").IsUnique().HasDatabaseName("ix_auth_sessions_jti");
                    b.ToTable("auth_sessions", (string)null);
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.Property<Guid>("RoleId").HasColumnType("uuid").HasColumnName("role_id");
                    b.HasKey("UserId", "RoleId").HasName("pk_user_roles");
                    b.HasIndex("RoleId").HasDatabaseName("ix_user_roles_role_id");
                    b.ToTable("user_roles", (string)null);
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId").HasColumnType("uuid").HasColumnName("role_id");
                    b.Property<string>("Permission").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("permission");
                    b.HasKey("RoleId", "Permission").HasName("pk_role_permissions");
                    b.HasIndex("Permission").HasDatabaseName("ix_role_permissions_permission");
                    b.ToTable("role_permissions", (string)null);
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.AuthSession", b =>
                {
                    b.HasOne("GameNet.Server.Modules.Identity.Domain.OperatorUser", null).WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                        .HasConstraintName("fk_auth_sessions_operator_users_user_id");
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("GameNet.Server.Modules.Identity.Domain.OperatorUser", null).WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                        .HasConstraintName("fk_user_roles_operator_users_user_id");
                    b.HasOne("GameNet.Server.Modules.Identity.Domain.Role", null).WithMany()
                        .HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");
                });
            modelBuilder.Entity("GameNet.Server.Modules.Identity.Domain.RolePermission", b =>
                {
                    b.HasOne("GameNet.Server.Modules.Identity.Domain.Role", null).WithMany()
                        .HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

#pragma warning restore 612, 618
        }
    }
}
